steps:
- name: Checkout code
  uses: actions/checkout@v2

- name: Set up Go
  uses: actions/setup-go@v2
  with:
    go-version: '1.23'

- name: Verify go.mod exists
  run: ls -l go.mod

- name: Install dependencies
  run: go mod tidy
